version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=mynameisanything
      - BCRYPT_ROUNDS=10
      - MONGODB_URI=mongodb://mongo:27017/timemachine
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: